%YAML:1.0

# Camera calibration and distortion parameters (OpenCV)

Camera.fx: 672.9608978119336
Camera.fy: 673.1982794389919
Camera.cx: 329.7185398185948
Camera.cy: 247.4384152909337

Camera.k1: 0.03495880188634037
Camera.k2: -0.1519203384741501
Camera.p1: 0.001540347072154785
Camera.p2: 0.002177169266503919
Camera.k3: 0.0

Camera.width: 640 #OK
Camera.height: 480 #OK

# Camera frames per second
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7
